### PR TITLE
fsfuzzer test got ported

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Signed-off-by: praveen@linux.vnet.ibm.com
added fsfuzzer Test case

### CODE REVIEW

**Comment by apahim** [comment]
Could you please squash the commits into one commit only?

**Comment by PraveenPenguin** [comment]
@apahim  thanks for looking this , will commit code in  single commit.

**Comment by PraveenPenguin** [comment]
Added fsfuzzer to avocado #57 
open a new pull request in a single commit

**Comment by PraveenPenguin** [comment]
@apahim committed code in single commit in #57 can you please review .

**Pull request closed without merging**
