### PR TITLE
generic.ltp: Few adjustments

### PR DESCRIPTION
**Pull request by ldoktor**
This PR contains few adjustments to the `generic/ltp` test. Please see the commit messages for details.

**This requires the https://github.com/avocado-framework/avocado/pull/1256 PR applied.**

### CODE REVIEW

**Comment by ldoktor** [comment]
Hello @santhosh93, this adds few fixes to test you added. There is one big issue in avocado due which this does not work. I'll try to fix it but if it turns out to be too complex, I'll push this without the last commit.

**Comment by ldoktor** [comment]
@apahim, @clebergnu I retested it and it seems to be working fine with the `zip` fix included. Would you please merge this as it contains fixes to possible false-positives?

**Comment by clebergnu** [comment]
Still failing for me:

```
[stdout] INFO: ltp-pan reported some tests FAIL

Reproduced traceback from: /home/cleber/src/avocado/avocado/avocado/core/test.py:448
Traceback (most recent call last):
  File "/home/cleber/src/avocado/avocado-misc-tests/generic/ltp.py", line 83, in test
    self.fail("LTP tests failed: %s" % ", ".join(failed_tests))
  File "/home/cleber/src/avocado/avocado/avocado/core/test.py", line 598, in fail
    raise exceptions.TestFail(message)
TestFail: LTP tests failed: abort01, abort01, ftruncate04, ftruncate04, kill11, kill11, sched_rr_get_interval01, sched_rr_get_interval01, sched_rr_get_interval02, sched_rr_get_interval02, sched_rr_get_interval03, sched_rr_get_interval03, sched_setparam02, sched_setparam02, sched_setparam03, sched_setparam03, semctl06, semctl06, semctl06, semctl06, semctl06, semctl06, semctl06, vhangup02, gf17, gf18

FAIL 1-generic/ltp.py:ltp.test -> TestFail: LTP tests failed: abort01, abort01, ftruncate04, ftruncate04, kill11, kill11, sched_rr_get_interval01, sched_rr_get_interval01, sched_rr_get_interval02, sched_rr_get_interval02, sched_rr_get_interval03, sched_rr_get_interval03, sched_setparam02, sched_setparam02, sched_setparam03, sched_setparam03, semctl06, semctl06, semctl06, semctl06, semctl06, semctl06, semctl06, vhangup02, gf17, gf18
```

I'll investigate it further.

**Comment by ldoktor** [comment]
Well some tests fail on my machine too, it does not mean the test is wrong, it just means it does not work on your os+gcc+machine. One think which is clear from your report is that we should use set and not list for tests as the failed tests are reported multiple times...

**Comment by ldoktor** [comment]
@clebergnu how did your investigation turned out?

**Comment by apahim** [comment]
Ping @clebergnu, @ldoktor, still relevant? Last comment is 1month old.

**Comment by ldoktor** [comment]
yes, it should be applied as it improves the reporting and avoids false-positives.

**Comment by sathnaga** [comment]
ACKed

**Pull request merged**
