### PR TITLE
Added Oprofile test which covers oprofile test scenarios-v2

### PR DESCRIPTION
**Pull request by poojabs7**
Added code for displaying failed tests.

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@poojabs7 facing some issue while running this test  as oprofile git not available 

```
[stdout] Initialized empty Git repository in /var/tmp/avocado_pk0U0Y/1-oprofile.py_Oprofile.test/src/.git/
Fetching git [REP 'git://oprofile.git.sourceforge.net/gitroot/oprofile/oprofile-tests' BRANCH 'master'] -> /var/tmp/avocado_pk0U0Y/1-oprofile.py_Oprofile.test/src
Running '/bin/git fetch -q -f -u -t git://oprofile.git.sourceforge.net/gitroot/oprofile/oprofile-tests master:master'
[stderr] fatal: Could not read from remote repository.
[stderr] 
[stderr] Please make sure you have the correct access rights
[stderr] and the repository exists.

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado-38.0-py2.7.egg/avocado/core/test.py:435
Traceback (most recent call last):
  File "/root/oprofile.py", line 45, in setUp
    'oprofile-tests', destination_dir=self.srcdir)
  File "/usr/lib/python2.7/site-packages/avocado-38.0-py2.7.egg/avocado/utils/git.py", line 201, in get_repo
    repo.execute()
  File "/usr/lib/python2.7/site-packages/avocado-38.0-py2.7.egg/avocado/utils/git.py", line 176, in execute
    self.fetch(self.uri)
  File "/usr/lib/python2.7/site-packages/avocado-38.0-py2.7.egg/avocado/utils/git.py", line 115, in fetch
    (uri, self.branch, self.lbranch))
  File "/usr/lib/python2.7/site-packages/avocado-38.0-py2.7.egg/avocado/utils/git.py", line 106, in git_cmd
    ignore_status=ignore_status)
  File "/usr/lib/python2.7/site-packages/avocado-38.0-py2.7.egg/avocado/utils/process.py", line 1033, in run
    raise CmdError(cmd, sp.result)
CmdError: Command '/bin/git fetch -q -f -u -t git://oprofile.git.sourceforge.net/gitroot/oprofile/oprofile-tests master:master' failed (rc=128)

ERROR 1-oprofile.py:Oprofile.test -> TestSetupFail: Command '/bin/git fetch -q -f -u -t git://oprofile.git.sourceforge.net/gitroot/oprofile/oprofile-tests master:master' failed (rc=128)

Test results available in /var/lib/libvirt/images/avocado/results/job-2016-08-18T14.29-76de395
[root@localhost ~]# 
```

may be git got moved in other location can please double check

**Comment by PraveenPenguin** [comment]
or may be access issue 

```
[praveen@localhost localavacado]$ git clone git://oprofile.git.sourceforge.net/gitroot/oprofile/oprofile-tests
Cloning into 'oprofile-tests'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[praveen@localhost localavacado]$ 
```

please guide

**Comment by apahim** [comment]
@poojabs7 @PraveenPenguin, let's conclude the discussion here and, if it's the case to send a new PR, please send it to: https://github.com/avocado-framework-tests/avocado-misc-tests.
This repository is frozen and we will not process new pull requests here anymore.

**Comment by PraveenPenguin** [comment]
@poojabs7 can you please close this as this PR was merged in  https://github.com/avocado-framework-tests/avocado-misc-tests

Regards
Praveen

**Comment by poojabs7** [comment]
Closing this PR as this Pr is merged

**Pull request closed without merging**
