### PR TITLE
Adding NVMe cli tests [v2]

### PR DESCRIPTION
**Pull request by narasimhan-v**
Signed-off-by: Narasimhan V sim@linux.vnet.ibm.com

### CODE REVIEW

**Comment by apahim** [comment]
Please provide the job.log with the results of this test.

**Comment by PraveenPenguin** [comment]
@narasimhan-v  as yesterday we had a discussion , facing a issue while running the test in my env 

```
are.1 nvme-intel-lat-stats.1 nvme-write.1 nvme-flush.1 nvme-smart-log.1 nvme-list.1 nvme-security-send.1 nvme-intel-id-ctrl.1 nvme-intel-market-name.1 nvme-security-recv.1 nvme-lnvm-info.1 nvme-intel-temp-stats.1 nvme-fw-activate.1 nvme-write-zeroes.1 nvme-fw-download.1 nvme-lnvm-remove.1 nvme-error-log.1 nvme-get-log.1 nvme-detach-ns.1 nvme-lnvm-list.1 nvme-admin-passthru.1 nvme-get-feature.1 nvme-help.1 nvme-lnvm-init.1 nvme-lnvm-create.1 nvme-lnvm-diag-set-bbtbl.1 nvme.1 /usr/local/share/man/man1
[stdout] make[1]: Leaving directory '/var/tmp/avocado_jT9yC0/2-nvmetest.py_NVMeTest.testwrite/src/nvme/Documentation'
PARAMS (key=device, path=*, default=/dev/nvme0) => '/dev/nvme0'
Running 'nvme show-regs /dev/nvme0 | grep version | awk '{print $NF}''
[stderr] /dev/nvme0: No such file or directory

Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-38.0-py2.7.egg/avocado/core/test.py:435
Traceback (most recent call last):
  File "/root/nvmetest.py", line 49, in setUp
    self.id_ns = self.create_namespace()
  File "/root/nvmetest.py", line 65, in create_namespace
    if int(process.system_output(cmd, shell=True).strip('\n')) < 10200:
ValueError: invalid literal for int() with base 10: ''

ERROR 2-nvmetest.py:NVMeTest.testwrite -> TestSetupFail: invalid literal for int() with base 10: ''

Test results available in /root/avocado/job-results/job-2016-08-16T01.18-ed076e9
root@localhost:~#
```

can you please help me on this not sure it is nvme device issue ?

**Comment by PraveenPenguin** [comment]
oh @apahim already asked for job log did not  notice that

**Comment by narasimhan-v** [comment]
@apahim @PraveenPenguin Looking into the issue.

**Comment by narasimhan-v** [comment]
@apahim @PraveenPenguin With all comments and errors addressed, and job.log attached, opened a new PR #147

**Pull request closed without merging**
