### PR TITLE
Adding Driver Bind test.

### PR DESCRIPTION
**Pull request by narasimhan-v**
Signed-off-by: Narasimhan V sim@linux.vnet.ibm.com

### CODE REVIEW

**Comment by narasimhan-v** [comment]
[job_log.txt](https://github.com/avocado-framework/avocado-misc-tests/files/428700/job_log.txt)

**Comment by PraveenPenguin** [comment]
@narasimhan-v here also facing issue 

```
Profiler disabled
PARAMS (key=timeout, path=*, default=None) => None
START 1-driver_bind_test.py:DriverBindTest.test
PARAMS (key=pci_device, path=*, default=0001:01:00.0) => '0001:01:00.0'
Running 'lspci -ks 0001:01:00.0 | awk 'END{print $NF}''
Command 'lspci -ks 0001:01:00.0 | awk 'END{print $NF}'' finished with 0 after 0.00217294692993s
[stdout] 
Running 'echo -n 0001:01:00.0 > /sys/bus/pci/drivers//unbind'
Command 'echo -n 0001:01:00.0 > /sys/bus/pci/drivers//unbind' finished with 2 after 0.000532865524292s
[stderr] /bin/sh: 1: cannot create /sys/bus/pci/drivers//unbind: Permission denied

Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py:448
Traceback (most recent call last):
  File "/home/praveen/driver_bind_test.py", line 53, in test
    process.run(cmd, shell=True, sudo=True)
  File "/usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/utils/process.py", line 1046, in run
    raise CmdError(cmd, sp.result)
CmdError: Command 'echo -n 0001:01:00.0 > /sys/bus/pci/drivers//unbind' failed (rc=2)

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py", line 503, in _run_avocado
    raise test_exception

CmdError: Command 'echo -n 0001:01:00.0 > /sys/bus/pci/drivers//unbind' failed (rc=2)

ERROR 1-driver_bind_test.py:DriverBindTest.test -> CmdError: Command 'echo -n 0001:01:00.0 > /sys/bus/pci/drivers//unbind' failed (rc=2)

Test results available in /root/avocado/job-results/job-2016-08-25T01.28-d2f2137
root@system:/home/praveen# 
```

 Permission issue, ran this test on Fedora 24 as well as ubuntu can you please advice .

Regards
Praveen

**Comment by narasimhan-v** [comment]
@PraveenPenguin the pci slot  0001:01:00.0 does not exist on your system.
Can you check once with an existing one? You can get it from the command `lspci`

**Comment by PraveenPenguin** [comment]
@narasimhan-v  thanks 

can we need to run lspci and grep default pci device than assigned in  self.slot 
for yaml entry we can check  "`provided  pci device not in listed in system`"  and `skip` the test ?

**Comment by narasimhan-v** [comment]
@PraveenPenguin yes, I currently do not have a check for devices not listed in lspci. I will add that check. is that fine ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v yes for me test look good , it up to you  but my suggestion if we can add that check it facilitate user need  not take care about edit pci device in test case (python file)

**Comment by apahim** [comment]
@narasimhan-v @PraveenPenguin, let's conclude the discussion here and, if it's the case to send a new PR, please send it to: https://github.com/avocado-framework-tests/avocado-misc-tests.
This repository is frozen and we will not process new pull requests here anymore.

**Comment by narasimhan-v** [comment]
@apahim Sure

**Comment by narasimhan-v** [comment]
Closing this.
Created a new [PR](https://github.com/avocado-framework-tests/avocado-misc-tests/pull/3) in the new repository.

**Pull request closed without merging**
