### PR TITLE
Adding trinity test to avocado[v2]

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Signed-off-by: praveen@linux.vnet.ibm.com
added trinity Test case
V1: #95 

```
v2:set the expire time for the asset file
v2:fix user permission to run script from non - root user
```

### CODE REVIEW

**Comment by apahim** [comment]
@PraveenPenguin the permission issue is gone. Now I'm facing:

```
Running 'su - trinity -c " /home/trinity/trinity-master/trinity  -x madasive   -N 10"'
[stderr] No idea what syscall (madasive) is.
[stdout] Trinity 1.7pre  Dave Jones <davej@codemonkey.org.uk>
[stdout] shm:0x7f3340173000-0x7f334caefda0 (4 pages)
...
CmdError: Command 'su - trinity -c " /home/trinity/trinity-master/trinity  -x madasive   -N 10"' failed (rc=1)
```

**Comment by PraveenPenguin** [comment]
@apahim can you please provide me full log .

I am wondering about this becasue my RHEL7.2 LE system it works 
`CmdError: Command 'su - trinity -c " /home/trinity/trinity-master/trinity  -x madasive   -N 10"' failed (rc=1)`

Thanks in advance

**Comment by apahim** [comment]
@PraveenPenguin, it's a Fedora 23: https://paste.fedoraproject.org/394055/14692178/

**Comment by PraveenPenguin** [comment]
@apahim wondering , tried on Fedora24 and it seem me working fine , i have Fedora 24 ppc64le as KVM gust Please find log in below link 

https://paste.fedoraproject.org/394451/93031121/

I am using avocado 38 
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.5.2-302.fc24.ppc64le #1 SMP Thu Apr 28 14:45:10 UTC 2016 ppc64le ppc64le ppc64le GNU/Linux
[root@localhost ~]# cat /etc/issue
\S
Kernel \r on an \m (\l)

Admin Console: https://\4:9090/ or https://[\6]:9090/

[root@localhost ~]#

**Comment by apahim** [comment]
You have the same error in your log lines 568/569. The difference is that in your case the test goes ahead.

**Comment by PraveenPenguin** [comment]
@apahim thanks will fix this issue .

**Comment by PraveenPenguin** [comment]
@apahim created new PR 112 with fix.

Thanks

**Pull request closed without merging**
