### PR TITLE
Adding ezfio test for SSD devices [v2]

### PR DESCRIPTION
**Pull request by narasimhan-v**
Signed-off-by: Narasimhan V sim@linux.vnet.ibm.com

### CODE REVIEW

**Comment by narasimhan-v** [comment]
[job_log.txt](https://github.com/avocado-framework/avocado-misc-tests/files/428644/job_log.txt)

**Comment by PraveenPenguin** [comment]
@narasimhan-v can you please help me , still facing some issue while run 

```
Running '/usr/bin/git describe'
Command '/usr/bin/git describe' finished with 128 after 0.000940799713135s
[stderr] fatal: No names found, cannot describe anything.
git commit ID is ad758e031d287a76a79bb2fc09d451a106cce7cd (no tag found)
PARAMS (key=device, path=*, default=/dev/nvme0n1) => '/dev/nvme0n1'
PARAMS (key=utilization, path=*, default=100) => '100'
Running './ezfio.py -d /dev/nvme0n1 -o /root/avocado/job-results/job-2016-08-25T00.36-11cd48f/test-results/1-ezfiotest.py:EzfioTest.test/data -u 100 --yes'
[stdout] ERROR: Can't get '/dev/nvme0n1' size.  Incorrect device name?
Command './ezfio.py -d /dev/nvme0n1 -o /root/avocado/job-results/job-2016-08-25T00.36-11cd48f/test-results/1-ezfiotest.py:EzfioTest.test/data -u 100 --yes' finished with 1 after 0.105535030365s

Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py:448
Traceback (most recent call last):
  File "/home/praveen/ezfiotest.py", line 65, in test
    process.run(cmd, shell=True)
  File "/usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/utils/process.py", line 1046, in run
    raise CmdError(cmd, sp.result)
CmdError: Command './ezfio.py -d /dev/nvme0n1 -o /root/avocado/job-results/job-2016-08-25T00.36-11cd48f/test-results/1-ezfiotest.py:EzfioTest.test/data -u 100 --yes' failed (rc=1)

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/avocado-39.0-py2.7.egg/avocado/core/test.py", line 503, in _run_avocado
    raise test_exception

CmdError: Command './ezfio.py -d /dev/nvme0n1 -o /root/avocado/job-results/job-2016-08-25T00.36-11cd48f/test-results/1-ezfiotest.py:EzfioTest.test/data -u 100 --yes' failed (rc=1)

ERROR 1-ezfiotest.py:EzfioTest.test -> CmdError: Command './ezfio.py -d /dev/nvme0n1 -o /root/avocado/job-results/job-2016-08-25T00.36-11cd48f/test-results/1-ezfiotest.py:EzfioTest.test/data -u 100 --yes' failed (rc=1)

Test results available in /root/avocado/job-results/job-2016-08-25T00.36-11cd48f
root@system: /home/praveen# 
root@system:/home/praveen# 

```

I am running this test in ubuntu and my system does not have nvme device . Please advise 

Regards
Praveen

**Comment by narasimhan-v** [comment]
@PraveenPenguin my mistake. Did the check in nvme-cli test, but forgot to do it here.
Will rectify it and send a new PR shortly

**Comment by narasimhan-v** [comment]
@PraveenPenguin Created new PR #152 
Thanks

**Comment by PraveenPenguin** [comment]
@narasimhan-v  oh ok

**Pull request closed without merging**
