### PR TITLE
Enable travis check for every push/pull request.

### PR DESCRIPTION
**Pull request by apahim**
Signed-off-by: Amador Pahim apahim@redhat.com

### CODE REVIEW

**Comment by clebergnu** [comment]
Travis related patches that fail on Travis! The wonderful world of trial and error! :smile: 

Jokes aside, thanks for that! Much appreciated!

**Comment by apahim** [comment]
Damn, you're faster than a `git push -f` :)

**Comment by apahim** [comment]
(meaning "damn, I missed the requirements") :D

**Comment by clebergnu** [comment]
:)

**Pull request merged**
